# Generated by Django 5.2.1 on 2025-07-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='hover_icon',
            field=models.ImageField(blank=True, null=True, upload_to='services-icon/%Y/%m/%d', verbose_name='Hover Icon'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='services-icon/%Y/%m/%d', verbose_name='Icon'),
        ),
    ]
