# Generated by Django 5.2.1 on 2025-07-12 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_service_hover_icon_alter_service_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='icon',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='hover_icon',
        ),
    ]
